---
title: "ggplot part 2"
author: "j felton"
date: "2024-09-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packagaes

## shortcut to add code chunk
#option + cmd + i

```{r, message=FALSE}
library(tidyverse)
library(knitr)
library(scales)
```

<br>

#load data
```{r,message=FALSE}
coronavirus <- read_csv('https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv')

max(coronavirus$date)
```

the latest date for which we have data is `r max(coronavirus$date)`

```{r}
coronavirus |>
  head(6) |>
  kable()
```

```{r}
coronavirus |>
  filter(date == max(date)) |>
  group_by(type) |>
  summarise(cases=sum(cases)) |>
  kable(format.args = list(decimal.mark = '.',big.mark= ','))
```


```{r}
coronavirus |>
  filter(type == 'confirmed') |> 
  group_by(date) |> 
  summarise(total_cases = sum(cases)) |> 
  ggplot(aes(x=date,y=total_cases)) +
  geom_line() +
  scale_y_continuous(labels = label_comma())  ##i want to use the label comma argument from the scales package
```
<br>
```{r}
gg_base <- coronavirus |>
  filter(type == 'confirmed') |> 
  group_by(date,country) |> 
  summarise(total_cases = sum(cases)) |> 
  ggplot(aes(x=date,y=total_cases, color = country)) +
  scale_y_continuous(labels = label_comma())

top5_country  <- coronavirus |> 
  filter(type == 'confirmed') |> 
  group_by(date,country) |> 
  summarise(total_cases = sum(cases)) |> 
  arrange(-total_cases) |> 
  head(5) |> 
  pull(country)

coronavirus |> 
  filter(type== "confirmed", country %in% top5_country, cases >= 0)

top5_country


gg_base +
  geom_col()

#alpha changes the transparency

gg_base + 
  geom_point(aes(size = total_cases,
                 color = total_cases),
 alpha = .05            ) + 
 theme_classic() + 
  theme(legend.background = element_rect(fill = "powderblue", color = "navy", linewidth = 1))
 

```

```{r}
gg_base +
  geom_col() +
  theme_bw() +
  labs(x = "date", y = "total confimred cases", title = str_c("daily counts of new corna virus cases record per ", max(coronavirus$date)))
```

```{r}
gg_base +
  geom_col() +
  geom_line(aes(class("country"))) +
  theme_bw() +
  labs(x = "date", y = "total confimred cases", title = str_c("daily counts of new corna virus cases record per ", max(coronavirus$date)))
```


```{r}
coronavirus |> 
  filter(type=="confimred", country %in% top5_country,cases >= 0 ) |> 
  group_by(country) |> 
  summarise(total_cases)
```


```{r}
top5_countries <- coronavirus |> 
  filter(type == "confirmed") |>
  group_by(country) |>
  summarize(total_cases = sum(cases)) |>
  arrange(-total_cases) |> 
  head(5) |> 
  pull(country)

coronavirus |>  
  filter(type == "confirmed", country %in% top5_countries, cases >= 0) |> 
  group_by(country, date) |> 
  summarize(total_cases = sum(cases)) |>  # Need this summarize because some countries have data broken down by Province.State
  ggplot(mapping = aes(x = date, y = total_cases, color = country)) +
  geom_line()

coronavirus |>  
  filter(type == "confirmed", country %in% top5_countries, cases >= 0) |> 
  group_by(country, date) |> 
  summarize(total_cases = sum(cases)) |> 
  ggplot(mapping = aes(x = date, y = total_cases)) +
  geom_line() +
  facet_wrap(~country)

coronavirus |> 
  filter(type == "confirmed" | type == "death", country %in% top5_countries, cases >= 0) |>
  group_by(country, type) |>
  summarize(cases = sum(cases)) |>
  ggplot() +
  geom_col(aes(x = country, y = cases, fill = type), position = "fill")
```


```{r}
vacc <- read_csv("https://raw.githubusercontent.com/RamiKrispin/coronavirus/main/csv/covid19_vaccine.csv")

# create a "total to date" subset of the data
vacc_ttd <- vacc |> 
  filter(date == max(date), !is.na(people_at_least_one_dose), !is.na(population))

# Let's look at our new tibble so make sure it makes sense
vacc_ttd

vacc_ttd |> 
  ggplot() +
  geom_label(mapping = aes(population, people_at_least_one_dose, label = country_region))

```

```{r}
vacc_ttd |> 
  filter(population > 50000000) |> 
  ggplot() +
  geom_label(mapping = aes(log(population), people_at_least_one_dose, label = country_region))

```

